### ISSUE TITLE
truncate: /tmp/occambsd/occambsd.raw: No space left on device

### ISSUE THREAD

**Issue by infostud** [michaeldexter/occambsd#1]
```
# uname -a
FreeBSD jadzia 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
# sysctl hw | grep mem:
hw.physmem: 8443011072
hw.usermem: 1356660736
hw.realmem: 8589934592
# grep -n imagesize occambsd.sh
84:imagesize="4G"				# More than enough room
267:	truncate -s "$imagesize" "$work_dir/occambsd.raw" || \
# truncate -s 4G /tmp/occambsd/occambsd.raw
truncate: /tmp/occambsd/occambsd.raw: No space left on device
# mount | grep occambsd
tmpfs on /tmp/occambsd (tmpfs, local)
# truncate -s 4G /tmp/occambsd/../occambsd.raw
#
```
I got it working by changing all occurrences to `$work_dir/../occambsd.raw` in `occambsd.sh` but this probably isn't ideal.

**Comment by michaeldexter** [comment]
Did you find that 4G was inadequate or you ran out of RAM because of tmpfs?

**Comment by infostud** [comment]
4GB for the disk image is fine. With only 8GB of system RAM it exhausts RAM when truncating. I've upgraded this development machine to 16GB. I'll see if that makes a difference.

**Comment by michaeldexter** [comment]
I bumped the image to 5G just in case.

**Comment by michaeldexter** [comment]
I run out of RAM too on one bank of lab machines with 8G RAM. I have just pushed the first changes to make tmpfs optional.

**Comment by infostud** [comment]
I created TinyPCs reducing a FreeBSD distribution (kernel+userland) by hand. Students would run with QEMU on Windows, and make virtual network labs eg, client <-> router <-> server (dhcp, dns, http) in 2008. The disk image was about 100MB
<img width="723" alt="Screen Shot 2022-03-11 at 6 07 10 pm" src="https://user-images.githubusercontent.com/3540729/157819183-e5ce91b2-fbce-4664-88a9-3e39ba93d62f.png">
.

**Comment by michaeldexter** [comment]
Nice

**Comment by michaeldexter** [comment]
I have make tmpfs optional.
