### ISSUE TITLE
Why test for GENERIC kernel config while cleaning up the jail?

### ISSUE THREAD

**Issue by ngortheone** [michaeldexter/occambsd#3]
Hi @michaeldexter, the genius of your thought escapes me. Can you elaborate why do you test for presence of a `GENERIC` kernel config file for `amd64` here? AFAIK this file always exists and this check is sort of redundant.

```
[ -f $src_dir/sys/amd64/conf/GENERIC ] || \

... # skipping comments in between
jls | grep -q occambsd && jail -r occambsd
```

**Comment by michaeldexter** [comment]
Ihor,

It is a simple test for an absent source tree. The GENERIC kernconf will 
not exists on an installation if src.txz is not selected.

**Comment by michaeldexter** [comment]
Or any sources from any origin for that matter. You'd be surprised how many developers perform zero "look before you leap" tests.

Re-open this if you are still confused.
